/**
 * One-time setup. Run setup() from the Apps Script editor (Run ▸ setup) while signed in
 * as the account that should own the data. It creates the Spreadsheet, builds the tabs,
 * seeds the 5 designations + KPIs, and registers you as the first admin.
 * Safe to re-run: it will NOT overwrite existing data — it only creates what's missing.
 */
function setup() {
  var props = PropertiesService.getScriptProperties();
  var id = props.getProperty(PROP_SHEET_ID);
  var ss;
  if (id) {
    ss = SpreadsheetApp.openById(id);
  } else {
    ss = SpreadsheetApp.create('Clustox CBPMS — Data (do not edit by hand)');
    props.setProperty(PROP_SHEET_ID, ss.getId());
    // remove the default empty sheet later, after tabs exist
  }

  var headers = {};
  headers[TABS.CONFIG]       = ['key','value'];
  headers[TABS.DESIGNATIONS] = ['id','name','identity'];
  headers[TABS.KPIS]         = ['designationId','kpiId','name','weight','desc','question','evidence'];
  headers[TABS.BEHAVIORS]    = ['designationId','behaviorId','name','desc','question'];
  headers[TABS.EMPLOYEES]    = ['id','name','email','designationId','department','manager','project','empType','addedAt','empCode'];
  headers[TABS.ASSIGNMENTS]  = ['reviewerEmail','employeeId'];
  headers[TABS.REVIEWS]      = REVIEW_COLS;

  Object.keys(headers).forEach(function (name) {
    var sh = ss.getSheetByName(name);
    if (!sh) { sh = ss.insertSheet(name); }
    if (sh.getLastRow() === 0) {
      sh.getRange(1, 1, 1, headers[name].length).setValues([headers[name]]).setFontWeight('bold');
      sh.setFrozenRows(1);
    } else {
      // Migrate an existing sheet: append any header columns it is missing
      // (added as the LAST columns so existing data stays aligned).
      var existing = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
      headers[name].forEach(function (h) {
        if (existing.indexOf(h) < 0) {
          sh.getRange(1, sh.getLastColumn() + 1).setValue(h).setFontWeight('bold');
          existing.push(h);
        }
      });
    }
  });

  // drop the auto-created "Sheet1" if still empty
  var def = ss.getSheetByName('Sheet1');
  if (def && ss.getSheets().length > 1) ss.deleteSheet(def);

  // register first admin
  var me = currentEmail_();
  if (!configGet_('admins')) {
    appendRow_(TABS.CONFIG, { key: 'admins', value: me }, ['key','value']);
  }

  // seed designations only if empty
  if (readTab_(TABS.DESIGNATIONS).length === 0) seedDesignations_();

  Logger.log('Setup complete. Spreadsheet id: ' + ss.getId());
  Logger.log('Admin: ' + me);
  Logger.log('Deploy the web app, then open its URL.');
}

/** Add another admin by email (run from the editor, or manage the Config tab via the app later). */
function addAdmin(email) {
  var v = configGet_('admins') || '';
  var list = v.split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(String);
  email = String(email || '').trim().toLowerCase();
  if (email && list.indexOf(email) < 0) {
    list.push(email);
    var rows = readTab_(TABS.CONFIG).map(function (r) { if (r.key === 'admins') r.value = list.join(','); return r; });
    writeTab_(TABS.CONFIG, rows, ['key','value']);
  }
  Logger.log('Admins: ' + list.join(', '));
}

function seedDesignations_() {
  SEED.forEach(function (d) {
    appendRow_(TABS.DESIGNATIONS, { id: d.id, name: d.name, identity: d.identity }, ['id','name','identity']);
    d.kpis.forEach(function (k) {
      appendRow_(TABS.KPIS, { designationId: d.id, kpiId: k.id, name: k.name, weight: k.weight, desc: k.desc, question: k.question, evidence: k.evidence },
        ['designationId','kpiId','name','weight','desc','question','evidence']);
    });
    d.behaviors.forEach(function (b) {
      appendRow_(TABS.BEHAVIORS, { designationId: d.id, behaviorId: b.id, name: b.name, desc: b.desc, question: b.question },
        ['designationId','behaviorId','name','desc','question']);
    });
  });
}

// Faithful port of the current DEFAULT_DESIGS from src/App.jsx.
var BEH_BASE = [
  { id: 'b1', name: 'Professionalism & Accountability', desc: 'Reliability, ownership, punctuality, professional conduct, adherence to company expectations, and follow-through on commitments.', question: 'Can I consistently rely on this person to honor commitments and represent Clustox professionally?' },
  { id: 'b2', name: 'Collaboration & Communication', desc: 'Teamwork, responsiveness, respectful communication, stakeholder handling, and constructive conflict resolution.', question: 'Is this person someone others actively want to work with?' }
];
var BEH_LEAD = { id: 'b3', name: 'Leadership Behavior', desc: 'Positive influence, constructive feedback, team motivation, conflict handling, and role-model behavior appropriate to seniority.', question: 'Does this person elevate those around them?' };

var SEED = [
  { id: 'ase', name: 'Associate Software Engineer', identity: 'Learn, execute, collaborate, and grow.',
    kpis: [
      { id: 'k1', name: 'Delivery Ownership & Technical Excellence', weight: 30, desc: 'Delivers assigned tasks with quality while following engineering standards and validating work before handover.', question: 'Can this person reliably complete assigned work with minimal supervision and acceptable quality?', evidence: 'Completed tasks, PR feedback, QA feedback, rework/bug history, first-time quality.' },
      { id: 'k2', name: 'Product Thinking & Requirements Engineering', weight: 10, desc: 'Understands assigned requirements, asks clarifying questions, and connects tasks to the feature purpose.', question: 'Do they understand the purpose behind their assigned work?', evidence: 'Grooming participation, clarification questions, requirement notes, acceptance criteria alignment.' },
      { id: 'k3', name: 'Project Adaptability & Business Agility', weight: 15, desc: 'Adjusts to changing priorities, project needs, tools, and technologies without significant productivity loss.', question: 'Can they adapt without significant productivity loss?', evidence: 'Ramp-up speed, flexibility during priority changes, feedback from leads.' },
      { id: 'k4', name: 'Team Communication & Collaboration', weight: 15, desc: 'Communicates within the team, raises blockers early, responds promptly, and collaborates professionally.', question: 'Can I rely on them to communicate proactively within the team?', evidence: 'Slack/Jira updates, blocker communication, meeting participation, peer feedback.' },
      { id: 'k5', name: 'AI Fluency & Engineering Productivity', weight: 15, desc: 'Uses AI tools responsibly in daily work and validates AI-generated outputs before use.', question: 'Are they using AI to learn faster and become more productive?', evidence: 'Examples of AI-assisted coding, documentation, debugging, learning, and validation.' },
      { id: 'k6', name: 'Learning Agility & Skill Development', weight: 15, desc: 'Demonstrates consistent learning, skill growth, and openness to feedback.', question: 'Are they growing at the expected pace for their level?', evidence: 'Learning plan progress, manager feedback, training participation, improved independence.' }
    ], behaviors: BEH_BASE },
  { id: 'se', name: 'Software Engineer', identity: 'Independent contributor who owns features and collaborates across functions.',
    kpis: [
      { id: 'k1', name: 'Delivery Ownership', weight: 20, desc: 'Owns assigned features end-to-end with reliable follow-through, timely delivery, risk identification, and first-time quality.', question: 'Can I trust them to independently deliver features with minimal follow-up?', evidence: 'On-time delivery, low rework, low bug leakage, risk updates, completion against commitments.' },
      { id: 'k2', name: 'Technical Excellence', weight: 15, desc: 'Produces maintainable, testable, and standards-aligned solutions with sound technical judgment.', question: 'Is this person building reliable and maintainable solutions?', evidence: 'PR quality, code maintainability, test coverage, defect trends, design quality.' },
      { id: 'k3', name: 'Product Thinking & Requirements Engineering', weight: 15, desc: 'Understands feature context, dependencies, acceptance criteria, and business value.', question: 'Do they understand both the what and the why?', evidence: 'Grooming input, dependency identification, requirement gaps raised, implementation alignment.' },
      { id: 'k4', name: 'Project Adaptability & Business Agility', weight: 10, desc: 'Creates value across changing project needs, domains, tools, and priorities.', question: 'Can they create value wherever the business needs them?', evidence: 'Project transitions, ramp-up speed, domain learning, flexibility, lead feedback.' },
      { id: 'k5', name: 'Cross-Functional Collaboration & Stakeholder Communication', weight: 10, desc: 'Collaborates effectively with PMs, QA, Tech Leads, and other stakeholders while communicating status and blockers.', question: 'Can they independently collaborate across functions?', evidence: 'Updates, QA/PM feedback, planning discussions, blocker communication, stakeholder responsiveness.' },
      { id: 'k6', name: 'AI Fluency & Engineering Productivity', weight: 15, desc: 'Integrates AI into daily workflows while critically validating outputs and improving productivity.', question: 'Are they leveraging AI effectively and safely?', evidence: 'AI-assisted coding/debugging, prompt examples, productivity improvements, validation evidence.' },
      { id: 'k7', name: 'Team Enablement', weight: 10, desc: 'Supports junior engineers and contributes to team effectiveness through guidance and knowledge sharing.', question: 'Do they positively influence and support the team?', evidence: 'Pairing support, onboarding help, knowledge sharing, junior feedback.' },
      { id: 'k8', name: 'Organizational Contribution & Process Improvement', weight: 5, desc: 'Contributes to internal improvements, documentation, reusable assets, or process enhancements beyond assigned work.', question: 'Are they helping Clustox improve beyond their project tasks?', evidence: 'Process suggestions, documentation, templates, hiring support, internal initiatives.' }
    ], behaviors: BEH_BASE },
  { id: 'sse', name: 'Senior Software Engineer', identity: 'Technical leader who owns modules, mentors others, and builds client trust.',
    kpis: [
      { id: 'k1', name: 'Delivery Ownership', weight: 20, desc: 'Owns complex deliverables/modules with reliable execution, proactive risk management, and strong first-time quality.', question: 'Can I trust them to independently deliver complex work?', evidence: 'Module delivery, predictable execution, low rework, risk management, delivery reliability.' },
      { id: 'k2', name: 'Technical Excellence', weight: 15, desc: 'Raises the technical quality bar through strong design, maintainability, testability, and engineering standards.', question: 'Is this person raising the technical quality bar?', evidence: 'Code/design reviews, defect trends, technical decisions, quality standards, testability.' },
      { id: 'k3', name: 'Product Thinking & Requirements Engineering', weight: 15, desc: 'Understands module-level impact, dependencies, business outcomes, and requirement risks.', question: 'Do they understand the bigger picture of the module and client context?', evidence: 'Requirement analysis, module dependencies, risk identification, roadmap awareness.' },
      { id: 'k4', name: 'Mentorship & Team Enablement', weight: 15, desc: 'Develops other engineers through coaching, reviews, pairing, and knowledge sharing.', question: 'Do they make other engineers better?', evidence: 'Mentorship evidence, junior improvement, knowledge sessions, onboarding support.' },
      { id: 'k5', name: 'Stakeholder Communication & Client Trust', weight: 10, desc: 'Communicates independently with stakeholders/clients and handles escalations with context and recommendations.', question: 'Would I confidently put them in front of a client?', evidence: 'Client feedback, meeting ownership, escalation handling, clarity of updates.' },
      { id: 'k6', name: 'AI Fluency & Engineering Productivity', weight: 10, desc: 'Uses and promotes AI-enabled workflows that improve team productivity and quality.', question: 'Are they helping the team work smarter with AI?', evidence: 'Agentic workflows, AI guidance to others, reusable prompts/playbooks, productivity examples.' },
      { id: 'k7', name: 'Project Adaptability & Business Agility', weight: 10, desc: 'Maintains performance through changing priorities, domains, technologies, and project needs.', question: 'Can they maintain performance through change?', evidence: 'Transition feedback, complex project support, domain ramp-up, flexibility.' },
      { id: 'k8', name: 'Organizational Contribution & Process Improvement', weight: 5, desc: 'Improves engineering, delivery, QA, or operational processes beyond their immediate project role.', question: 'Are they making Clustox stronger?', evidence: 'Playbooks, standards, process improvements, hiring/interview contributions.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'principal-se', name: 'Principal Software Engineer', identity: 'Technical leader who owns modules, mentors others, and builds client trust.',
    kpis: [
      { id: 'k1', name: 'Delivery Ownership', weight: 20, desc: 'Owns complex deliverables/modules with reliable execution, proactive risk management, and strong first-time quality.', question: 'Can I trust them to independently deliver complex work?', evidence: 'Module delivery, predictable execution, low rework, risk management, delivery reliability.' },
      { id: 'k2', name: 'Technical Excellence', weight: 15, desc: 'Raises the technical quality bar through strong design, maintainability, testability, and engineering standards.', question: 'Is this person raising the technical quality bar?', evidence: 'Code/design reviews, defect trends, technical decisions, quality standards, testability.' },
      { id: 'k3', name: 'Product Thinking & Requirements Engineering', weight: 15, desc: 'Understands module-level impact, dependencies, business outcomes, and requirement risks.', question: 'Do they understand the bigger picture of the module and client context?', evidence: 'Requirement analysis, module dependencies, risk identification, roadmap awareness.' },
      { id: 'k4', name: 'Mentorship & Team Enablement', weight: 15, desc: 'Develops other engineers through coaching, reviews, pairing, and knowledge sharing.', question: 'Do they make other engineers better?', evidence: 'Mentorship evidence, junior improvement, knowledge sessions, onboarding support.' },
      { id: 'k5', name: 'Stakeholder Communication & Client Trust', weight: 10, desc: 'Communicates independently with stakeholders/clients and handles escalations with context and recommendations.', question: 'Would I confidently put them in front of a client?', evidence: 'Client feedback, meeting ownership, escalation handling, clarity of updates.' },
      { id: 'k6', name: 'AI Fluency & Engineering Productivity', weight: 10, desc: 'Uses and promotes AI-enabled workflows that improve team productivity and quality.', question: 'Are they helping the team work smarter with AI?', evidence: 'Agentic workflows, AI guidance to others, reusable prompts/playbooks, productivity examples.' },
      { id: 'k7', name: 'Project Adaptability & Business Agility', weight: 10, desc: 'Maintains performance through changing priorities, domains, technologies, and project needs.', question: 'Can they maintain performance through change?', evidence: 'Transition feedback, complex project support, domain ramp-up, flexibility.' },
      { id: 'k8', name: 'Organizational Contribution & Process Improvement', weight: 5, desc: 'Improves engineering, delivery, QA, or operational processes beyond their immediate project role.', question: 'Are they making Clustox stronger?', evidence: 'Playbooks, standards, process improvements, hiring/interview contributions.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'sr-architect', name: 'Senior Software Architect', identity: 'Technical leader who owns modules, mentors others, and builds client trust.',
    kpis: [
      { id: 'k1', name: 'Delivery Ownership', weight: 20, desc: 'Owns complex deliverables/modules with reliable execution, proactive risk management, and strong first-time quality.', question: 'Can I trust them to independently deliver complex work?', evidence: 'Module delivery, predictable execution, low rework, risk management, delivery reliability.' },
      { id: 'k2', name: 'Technical Excellence', weight: 15, desc: 'Raises the technical quality bar through strong design, maintainability, testability, and engineering standards.', question: 'Is this person raising the technical quality bar?', evidence: 'Code/design reviews, defect trends, technical decisions, quality standards, testability.' },
      { id: 'k3', name: 'Product Thinking & Requirements Engineering', weight: 15, desc: 'Understands module-level impact, dependencies, business outcomes, and requirement risks.', question: 'Do they understand the bigger picture of the module and client context?', evidence: 'Requirement analysis, module dependencies, risk identification, roadmap awareness.' },
      { id: 'k4', name: 'Mentorship & Team Enablement', weight: 15, desc: 'Develops other engineers through coaching, reviews, pairing, and knowledge sharing.', question: 'Do they make other engineers better?', evidence: 'Mentorship evidence, junior improvement, knowledge sessions, onboarding support.' },
      { id: 'k5', name: 'Stakeholder Communication & Client Trust', weight: 10, desc: 'Communicates independently with stakeholders/clients and handles escalations with context and recommendations.', question: 'Would I confidently put them in front of a client?', evidence: 'Client feedback, meeting ownership, escalation handling, clarity of updates.' },
      { id: 'k6', name: 'AI Fluency & Engineering Productivity', weight: 10, desc: 'Uses and promotes AI-enabled workflows that improve team productivity and quality.', question: 'Are they helping the team work smarter with AI?', evidence: 'Agentic workflows, AI guidance to others, reusable prompts/playbooks, productivity examples.' },
      { id: 'k7', name: 'Project Adaptability & Business Agility', weight: 10, desc: 'Maintains performance through changing priorities, domains, technologies, and project needs.', question: 'Can they maintain performance through change?', evidence: 'Transition feedback, complex project support, domain ramp-up, flexibility.' },
      { id: 'k8', name: 'Organizational Contribution & Process Improvement', weight: 5, desc: 'Improves engineering, delivery, QA, or operational processes beyond their immediate project role.', question: 'Are they making Clustox stronger?', evidence: 'Playbooks, standards, process improvements, hiring/interview contributions.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'mgr-sd', name: 'Manager Software Development', identity: 'Hands-on engineering manager who owns team delivery, develops people, and maintains personal technical depth.',
    kpis: [
      { id: 'k1', name: 'Team Delivery Performance', weight: 20, desc: 'Owns the team\'s overall delivery outcomes — reliability, quality, and predictability across all active projects — while personally contributing to delivery on complex or high-priority work.', question: 'Can I trust this manager to keep their team delivering consistently while staying hands-on where it matters?', evidence: 'Sprint commitment rate, delivery failure frequency, personal contribution to high-priority deliverables, project lead feedback.' },
      { id: 'k2', name: 'Technical Excellence & Standards', weight: 15, desc: 'Maintains personal technical depth and sets the engineering quality bar for the team through code reviews, design decisions, and technical standards enforcement.', question: 'Is this manager raising the technical quality bar both personally and across their team?', evidence: 'Code/design review quality, defect trends, technical decisions, engineering standards adoption, PR feedback quality.' },
      { id: 'k3', name: 'People Development & Performance Management', weight: 20, desc: 'Develops direct reports through structured 1:1s, feedback, coaching, and performance management. Proactively identifies and acts on underperformance.', question: 'Are their engineers growing, and are performance issues being addressed proactively?', evidence: 'Performance review completeness, measurable direct report growth, 1:1 regularity, PIP initiation where needed, direct report feedback.' },
      { id: 'k4', name: 'Stakeholder & Client Leadership', weight: 15, desc: 'Manages client and senior stakeholder relationships at the project level. Owns escalations, communicates proactively, and resolves issues without requiring director involvement.', question: 'Would I confidently put this manager in front of a senior client or stakeholder?', evidence: 'Client feedback, escalation resolution rate, missed update frequency, management assessment of stakeholder communication.' },
      { id: 'k5', name: 'AI Fluency & Engineering Productivity', weight: 10, desc: 'Personally uses AI tools effectively and drives adoption across the team through practical examples, guidance, and setting expectations for responsible AI use.', question: 'Is this manager helping their team work smarter with AI?', evidence: 'Personal AI tool usage, team-level AI adoption evidence, productivity improvements, AI guidance provided to engineers.' },
      { id: 'k6', name: 'Billability & Team Placement', weight: 10, desc: 'Keeps the team continuously placed on billable client work through active development, performance management, and readiness planning.', question: 'Is the team continuously billable, and is the manager actively managing placement gaps?', evidence: 'Team billability rate, placement gap frequency, readiness interventions, management assessment of team client-readiness.' },
      { id: 'k7', name: 'Hiring Quality & Organizational Contribution', weight: 5, desc: 'Makes quality hiring decisions, contributes to engineering process improvements, and builds internal capability beyond day-to-day project delivery.', question: 'Are they making Clustox stronger through better hiring and internal contribution?', evidence: 'Hire performance over 6–12 months, interview feedback timeliness, process improvements implemented, internal initiatives led.' },
      { id: 'k8', name: 'Business Agility & Strategic Execution', weight: 5, desc: 'Adapts the team to changing business needs, priorities, and technologies without losing delivery momentum or team cohesion.', question: 'Can this manager keep their team productive and aligned through change?', evidence: 'Team transition feedback, ramp-up speed on new projects, flexibility under priority changes, lead and management feedback.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'ast', name: 'Associate Software Tester', identity: 'Learn to test, build quality habits, and develop the professional foundations of a QA engineer.',
    kpis: [
      { id: 'k1', name: 'Test Execution Accuracy & Completeness', weight: 30, desc: 'Executes assigned test cases thoroughly and accurately within the sprint cycle, documenting results clearly and completely.', question: 'Can this tester reliably execute assigned test cases with acceptable accuracy and documentation?', evidence: 'Percentage of assigned test cases executed per sprint, defects missed during testing, quality of test execution documentation assessed by senior review.' },
      { id: 'k2', name: 'Defect Reporting Quality', weight: 20, desc: 'Documents and communicates defects clearly and completely so they can be actioned without follow-up clarification.', question: 'Are their defect reports actionable without requiring clarification?', evidence: 'Percentage of defect reports actionable without follow-up, senior review of defect report quality, rate of reports returned for insufficient detail.' },
      { id: 'k3', name: 'Test Case Writing Development', weight: 15, desc: 'Develops the ability to write clear, reusable, and comprehensive test cases under guidance, improving quality across consecutive sprints.', question: 'Are they improving at writing test cases at the expected pace for their level?', evidence: 'Test case quality assessed through senior engineer review, improvement across consecutive sprints, adoption of feedback in subsequent submissions.' },
      { id: 'k4', name: 'AI Tool Utilization & Critical Adoption', weight: 15, desc: 'Meaningfully incorporates AI tools into day-to-day testing activities — using AI thoughtfully, critically validating outputs, and not blindly accepting results.', question: 'Are they using AI to learn faster and test smarter, with appropriate critical validation?', evidence: 'Manager observation of AI tool usage in testing workflow, quality of AI-assisted test cases and defect reports, evidence of validation rather than blind acceptance.' },
      { id: 'k5', name: 'Learning & Certification Progress', weight: 10, desc: 'Demonstrates commitment to building testing knowledge and progressing toward the first professional QA certification.', question: 'Are they growing their QA knowledge at the expected pace and working toward ISTQB Foundation or equivalent?', evidence: 'Progress toward ISTQB Foundation Level or equivalent, evidence of learning applied in day-to-day testing, senior engineer observation.' },
      { id: 'k6', name: 'Process Discipline & HR Compliance', weight: 10, desc: 'Demonstrates professional reliability across scrum participation, tool hygiene, and HR compliance expectations.', question: 'Can I rely on this person to meet process and compliance expectations consistently?', evidence: 'Scrum attendance rate, accuracy and timeliness of defect and test case updates in tools, zero unresolved HR compliance issues.' }
    ], behaviors: BEH_BASE },
  { id: 'st-manual', name: 'Software Tester (Manual)', identity: 'Independent manual tester who owns test coverage, finds meaningful defects, and begins building automation capability.',
    kpis: [
      { id: 'k1', name: 'Manual Test Coverage & Execution Quality', weight: 25, desc: 'Independently plans, designs, and executes thorough manual testing that provides genuine confidence in the software being shipped.', question: 'Can I trust their manual test coverage to catch what matters before release?', evidence: 'Percentage of acceptance criteria covered by documented test cases, post-release defects attributable to inadequate coverage, quality of test plans assessed by senior review.' },
      { id: 'k2', name: 'Defect Detection Effectiveness', weight: 20, desc: 'Finds defects that matter by thinking critically about where software is likely to fail, not just executing scripts mechanically.', question: 'Are they finding the right defects, or letting important issues through?', evidence: 'Number of valid defects raised per sprint relative to scope, severity distribution of defects found, rate of defects escaping to later stages or client.' },
      { id: 'k3', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains the skills, professional conduct, and testing reliability required to remain continuously placed on billable client work.', question: 'Is this tester continuously billable and does their contribution meet client standards?', evidence: 'Continuity of billable project placement, line manager and project lead assessment of client-readiness, absence of placement gaps attributable to skill or conduct.' },
      { id: 'k4', name: 'Automation Learning Progress', weight: 15, desc: 'Actively builds foundational automation knowledge as a deliberate growth expectation at this level.', question: 'Are they making genuine progress toward automation capability?', evidence: 'Completion of at least one automation course within the performance year, evidence of practical automation exposure, progress against a committed learning plan reviewed each quarter.' },
      { id: 'k5', name: 'Test Documentation Quality', weight: 10, desc: 'Produces complete, accurate, and usable testing documentation that another team member can execute without explanation.', question: 'Is their testing documentation reliable and usable by others on the team?', evidence: 'Senior assessment of documentation quality, percentage of test cases executable by another team member without clarification, accuracy of test repositories maintained throughout the sprint.' },
      { id: 'k6', name: 'Collaboration & Process Discipline', weight: 10, desc: 'Works effectively within the development team, communicates quality risks proactively, and maintains operational hygiene in testing tools.', question: 'Do they raise quality risks early and keep testing tools and processes in good order?', evidence: 'Developer and team lead feedback on defect communication quality, frequency of quality risks raised proactively during sprint planning, accuracy of tool updates.' }
    ], behaviors: BEH_BASE },
  { id: 'sst-manual', name: 'Senior Software Tester (Manual)', identity: 'Quality leader who owns test strategy, mentors others, drives shift-left quality, and builds automation capability.',
    kpis: [
      { id: 'k1', name: 'Test Strategy Ownership & Quality Leadership', weight: 25, desc: 'Defines and owns a comprehensive test strategy, setting the standard for quality coverage and making confident go/no-go release recommendations.', question: 'Can I trust their test strategy and release recommendations to protect quality?', evidence: 'Quality of test strategy documents assessed by PM and management, percentage of quality risks identified at inception vs mid-sprint, accuracy of go/no-go recommendations against post-release outcomes.' },
      { id: 'k2', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains continuous placement on billable client work and demonstrates the quality leadership that senior-level placement requires.', question: 'Is this senior tester continuously billable and leading quality confidently on client projects?', evidence: 'Continuity of billable placement, client and project lead feedback on quality leadership, absence of placement gaps attributable to performance or conduct.' },
      { id: 'k3', name: 'Defect Prevention & Shift-Left Quality', weight: 20, desc: 'Moves quality earlier in the development process by identifying requirement gaps during planning and collaborating with developers before code is written.', question: 'Are they catching quality issues before development, not just after?', evidence: 'Reduction in late-stage defect discovery rate, frequency of requirements gaps identified during planning, developer feedback on early testing collaboration quality.' },
      { id: 'k4', name: 'Mentorship & Junior Development', weight: 15, desc: 'Produces tangible improvement in junior and mid-level test engineers being mentored through structured guidance and knowledge sharing.', question: 'Are the engineers they mentor measurably improving?', evidence: 'Demonstrable improvement in test quality of mentored engineers across consecutive review cycles, regularity of knowledge-sharing sessions, feedback from junior engineers.' },
      { id: 'k5', name: 'Automation Development Progress', weight: 10, desc: 'Actively progresses automation capability beyond foundational knowledge toward practical contribution and certification.', question: 'Are they making meaningful progress in automation as an explicit growth expectation at this level?', evidence: 'Completion of a structured automation certification within the performance year, evidence of practical automation contribution, progress against a committed development plan reviewed each quarter.' },
      { id: 'k6', name: 'Client Communication & Hiring Contribution', weight: 10, desc: 'Communicates quality status professionally with clients and contributes meaningfully to QA hiring decisions.', question: 'Can I trust their client communication and rely on their hiring input?', evidence: 'Client and project lead feedback on communication clarity, zero missed quality updates, interview feedback submitted within 24 hours for every candidate evaluated.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'sst-auto', name: 'Senior Software Tester (Manual + Automation)', identity: 'Senior quality engineer who leads integrated test strategy, owns automation coverage, mentors others, and drives shift-left quality.',
    kpis: [
      { id: 'k1', name: 'Test Strategy & Quality Leadership', weight: 25, desc: 'Defines and owns a comprehensive test strategy integrating manual and automation into a coherent, risk-based quality approach with confident release recommendations.', question: 'Can I trust their integrated test strategy and release recommendations to protect quality across both manual and automated testing?', evidence: 'Quality of integrated test strategy documents, percentage of quality risks identified at inception vs mid-sprint, accuracy of go/no-go recommendations against post-release outcomes.' },
      { id: 'k2', name: 'Automation Strategy & Coverage Growth', weight: 25, desc: 'Owns the automation function — strategically growing coverage, maintaining suite health, and leading the team\'s automation capability forward.', question: 'Is the automation suite growing in coverage, staying healthy, and reducing manual regression effort?', evidence: 'Automation coverage growth per quarter against targets, suite reliability rate, quality of automation framework assessed through peer and management review, reduction in manual regression effort.' },
      { id: 'k3', name: 'Billability & Placement Readiness', weight: 15, desc: 'Maintains continuous placement on billable client work across both manual and automation disciplines at senior level.', question: 'Is this tester continuously billable and contributing at senior level across both disciplines?', evidence: 'Continuity of billable placement, client and project lead feedback on testing and automation leadership quality, absence of placement gaps attributable to performance or conduct.' },
      { id: 'k4', name: 'Defect Prevention & Shift-Left Quality', weight: 15, desc: 'Embeds quality earlier in the development cycle through proactive requirements review, early collaboration with developers, and systematic risk identification.', question: 'Are they catching quality issues before development, not just after?', evidence: 'Reduction in late-stage defect discovery rate, frequency of requirements gaps identified during planning, developer feedback on early testing collaboration quality.' },
      { id: 'k5', name: 'Mentorship & QA Capability Building', weight: 10, desc: 'Produces tangible improvement in junior and mid-level QA engineers across both manual and automation disciplines through structured mentorship and guidance.', question: 'Are the engineers they mentor measurably improving in both manual testing and automation?', evidence: 'Demonstrable improvement in test quality and automation output of mentored engineers, regularity of knowledge-sharing sessions, feedback from junior engineers on practical impact.' },
      { id: 'k6', name: 'Client Communication & Hiring Contribution', weight: 10, desc: 'Communicates quality and automation status professionally with clients and contributes meaningfully to QA hiring decisions covering both manual and automation profiles.', question: 'Can I trust their client communication and rely on their hiring assessments for both manual and automation roles?', evidence: 'Client and project lead feedback on communication quality, zero missed quality updates, interview feedback submitted within 24 hours, quality of technical assessments covering both disciplines.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'pst-manual', name: 'Principal Software Tester (Manual)', identity: 'Senior QA leader who owns department-level quality standards, drives shift-left quality across the portfolio, and develops the QA function.',
    kpis: [
      { id: 'k1', name: 'Department-Level Quality Standards Ownership', weight: 25, desc: 'Maintains rigorous quality standards at the project level while actively identifying process gaps, proposing improvements, and driving those changes across the department through structured collaboration with management.', question: 'Are they raising the quality bar across the department, not just on their own project?', evidence: 'Quality of process improvement proposals, adoption of improvements across QA department, management assessment of cross-department quality impact, frequency of process gap identification.' },
      { id: 'k2', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains continuous engagement on billable client work at the most senior individual QA level, with the credibility and capability that demands.', question: 'Is this principal tester continuously engaged on high-value accounts and delivering at the expected senior level?', evidence: 'Continuity of billable engagement on high-value or complex accounts, management and project lead assessment of quality leadership quality, absence of engagement gaps.' },
      { id: 'k3', name: 'Defect Prevention & Shift-Left Quality Leadership', weight: 20, desc: 'Drives early quality intervention across multiple projects simultaneously, setting the standard for requirements-stage quality engagement.', question: 'Are they reducing late-stage defect rates across the portfolio through proactive early engagement?', evidence: 'Measurable reduction in late-stage defect discovery rates across the project portfolio, frequency of requirements and design-stage quality interventions led, project team feedback on shift-left contribution value.' },
      { id: 'k4', name: 'QA Capability Development & Mentorship', weight: 15, desc: 'Produces tangible improvement in the testing quality and professional capability of engineers across the QA department through structured training and mentorship.', question: 'Is the QA department measurably stronger because of their mentorship and training?', evidence: 'Demonstrable improvement in testing quality of QA engineers across the department, regularity and participant-assessed quality of training delivered, evidence of high-potential engineers progressing along designed development pathways.' },
      { id: 'k5', name: 'Client Communication & Senior Escalation Handling', weight: 10, desc: 'Owns senior client-facing quality communication and escalation management with full authority and documented resolution paths.', question: 'Can I trust them to manage senior client quality escalations with full ownership and professionalism?', evidence: 'Client and project lead feedback on clarity and authority of quality communications, senior escalations resolved with documented resolution paths, zero missed or delayed quality updates.' },
      { id: 'k6', name: 'AI Tool Strategy & Hiring Leadership', weight: 10, desc: 'Leads strategic AI tool governance across the QA function and contributes high-quality senior hiring decisions for manual QA profiles.', question: 'Are they advancing AI maturity in the QA function and raising the hiring bar?', evidence: 'Completeness and adoption of AI usage guidelines for QA, management assessment of AI recommendation strategic value, interview feedback submitted within 24 hours, hiring recommendation quality validated against hire outcomes.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'pst-auto', name: 'Principal Software Tester (Manual + Automation)', identity: 'Most senior QA individual contributor who owns the automation programme, drives department-level quality standards, and develops the entire QA function.',
    kpis: [
      { id: 'k1', name: 'Department-Level Quality & Automation Standards Ownership', weight: 25, desc: 'Maintains rigorous quality standards at the project level while driving process improvements and automation standards across the entire QA department.', question: 'Are they raising the quality and automation bar across the department, not just on their own project?', evidence: 'Quality of process and automation improvement proposals, department-wide adoption, management assessment of cross-department impact, frequency of process gap identification.' },
      { id: 'k2', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains continuous engagement on billable client work at the most senior individual QA level across both manual and automation disciplines.', question: 'Is this principal tester continuously engaged on high-value accounts and delivering across both disciplines at the expected level?', evidence: 'Continuity of billable engagement on high-value or complex accounts, management and project lead assessment of quality and automation leadership quality, absence of engagement gaps.' },
      { id: 'k3', name: 'Automation Strategy & Portfolio Coverage Growth', weight: 20, desc: 'Owns the organisation\'s automation programme — framework quality, coverage growth, and the strategic direction of automation adoption across all QA teams.', question: 'Is the automation programme growing coverage, staying healthy, and delivering measurable efficiency gains across the portfolio?', evidence: 'Automation coverage growth across the project portfolio per quarter, quality and maintainability of automation frameworks, suite reliability rates across projects, reduction in manual regression effort.' },
      { id: 'k4', name: 'QA Capability Development & Mentorship', weight: 15, desc: 'Produces tangible improvement in testing quality and automation output of engineers across the QA department through structured training and mentorship across both disciplines.', question: 'Is the QA department measurably stronger in both manual testing and automation because of their contribution?', evidence: 'Demonstrable improvement in testing quality and automation output of QA engineers, regularity and quality of training delivered, evidence of engineers progressing along designed manual-to-automation development pathways.' },
      { id: 'k5', name: 'Client Communication & Senior Escalation Handling', weight: 10, desc: 'Owns senior client-facing quality and automation communication with full authority, handling escalations with documented resolution paths.', question: 'Can I trust them to manage senior client quality and automation escalations with full ownership and professionalism?', evidence: 'Client and project lead feedback on communication authority and reliability, senior escalations resolved with documented resolution paths, zero missed or delayed quality updates on managed accounts.' },
      { id: 'k6', name: 'AI Tool Strategy & Hiring Leadership', weight: 10, desc: 'Leads strategic AI tool governance across the QA function and contributes high-quality senior hiring decisions covering both manual and automation profiles.', question: 'Are they advancing AI maturity in the QA function and raising the hiring bar across both profiles?', evidence: 'Completeness and adoption of AI usage guidelines for QA, management assessment of AI recommendation strategic value, interview feedback submitted within 24 hours, hiring recommendation quality validated against hire outcomes.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) },
  { id: 'ba', name: 'Business Analyst', identity: 'Independent BA contributor who produces quality requirements, supports delivery, and manages client communication professionally.',
    kpis: [
      { id: 'k1', name: 'Requirements Quality & Completeness', weight: 25, desc: 'Produces clear, complete, and usable requirements documentation — the primary output of the BA function — that engineering and QA can act on without ambiguity.', question: 'Can engineering and QA reliably build and test from this BA\'s requirements without rework or blockers?', evidence: 'Rate of development rework or sprint blockers attributable to requirements gaps, engineering and QA feedback on documentation quality, percentage of requirements signed off before development begins.' },
      { id: 'k2', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains the skills, professional conduct, and delivery reliability required to remain continuously placed on billable client projects.', question: 'Is this BA continuously billable and meeting the professional standards client-facing placement requires?', evidence: 'Continuity of billable project placement, line manager and project lead assessment of client-readiness and professional conduct, absence of placement gaps attributable to skill or conduct.' },
      { id: 'k3', name: 'Client & Stakeholder Communication Quality', weight: 20, desc: 'Communicates professionally and reliably with clients and stakeholders when placed on projects, following up on action items without needing to be chased.', question: 'Can I trust this BA to manage client communication independently and reliably?', evidence: 'Client and project lead feedback on communication quality and responsiveness, zero missed follow-ups on client action items, escalations handled promptly with full context.' },
      { id: 'k4', name: 'Delivery Coordination Effectiveness', weight: 15, desc: 'Supports the development team effectively through the sprint cycle — clear stories, timely clarifications, and proactive identification of scope creep.', question: 'Is this BA keeping delivery unblocked and scope under control?', evidence: 'Frequency of sprint blockers attributable to late or missing BA input, engineering feedback on quality and timeliness of clarifications, proactive scope creep identification assessed by project lead.' },
      { id: 'k5', name: 'AI Tool Integration', weight: 10, desc: 'Uses AI tools actively and effectively to improve the quality and efficiency of BA work, critically validating AI-generated content before use.', question: 'Are they using AI to produce better requirements and documentation faster, with appropriate validation?', evidence: 'Manager and project lead observation of AI tool usage in workflow, quality of AI-assisted documentation through peer review, evidence of critical validation before client or engineering use.' },
      { id: 'k6', name: 'Learning & Professional Development', weight: 10, desc: 'Demonstrates commitment to building BA competency and domain knowledge beyond day-to-day delivery, progressing toward professional certification.', question: 'Are they growing their BA capability at the expected pace and working toward a recognised certification?', evidence: 'Progress toward a recognised BA certification, evidence of domain knowledge applied in requirements quality improvements, peer and project lead feedback on observable growth in facilitation and communication skills.' }
    ], behaviors: BEH_BASE },
  { id: 'sr-ba', name: 'Senior Business Analyst', identity: 'Senior BA who leads requirements quality across multiple projects, manages senior stakeholders, mentors junior BAs, and contributes to BA function standards.',
    kpis: [
      { id: 'k1', name: 'Requirements Quality & Completeness', weight: 25, desc: 'Produces and oversees clear, complete, traceable requirements documentation across multiple assigned projects — enabling engineering and QA to deliver without rework or ambiguity.', question: 'Can I trust that requirements across their projects are complete, traceable, and signed off before development begins?', evidence: 'Rate of development rework or blockers across managed projects, engineering and QA feedback on requirements quality, percentage of requirements fully signed off across all managed projects per quarter.' },
      { id: 'k2', name: 'Billability & Placement Readiness', weight: 20, desc: 'Maintains continuous placement on billable client projects and demonstrates the senior BA credibility that high-value client work requires.', question: 'Is this senior BA continuously billable and contributing at the senior level clients expect?', evidence: 'Continuity of billable placement, client and project lead assessment of BA contribution quality and client relationship management, absence of placement gaps attributable to performance or conduct.' },
      { id: 'k3', name: 'Client & Stakeholder Management Quality', weight: 20, desc: 'Manages senior client relationships strategically and professionally, resolving complex stakeholder conflicts and scope disagreements without requiring management escalation.', question: 'Would I confidently put this senior BA in front of a senior or difficult client stakeholder?', evidence: 'Client feedback on communication quality and reliability across managed accounts, zero missed follow-ups, complex stakeholder conflicts or scope disagreements resolved at BA level.' },
      { id: 'k4', name: 'Delivery Coordination & Scope Management', weight: 15, desc: 'Keeps delivery aligned with agreed requirements, runs effective backlog refinement, and manages change through the correct governance process across all managed projects.', question: 'Are their projects staying on scope, and is change being managed properly?', evidence: 'Frequency and quality of backlog refinement sessions led, rate of unmanaged scope creep identified by project lead, change requests assessed and communicated within agreed timelines.' },
      { id: 'k5', name: 'Mentorship & BA Function Contribution', weight: 10, desc: 'Produces tangible improvement in junior BAs and actively contributes to raising BA function standards through templates, guides, and process improvements.', question: 'Are junior BAs improving because of their mentorship, and are they making the BA function stronger?', evidence: 'Demonstrable improvement in requirements quality and client communication of mentored BAs, regularity of knowledge-sharing, at least one BA template or process improvement contributed per quarter.' },
      { id: 'k6', name: 'AI Tool Fluency & Learning', weight: 10, desc: 'Demonstrates advanced and responsible use of AI tools across the full BA workflow and contributes to raising AI literacy across the BA function.', question: 'Are they using AI at an advanced level and helping other BAs use it better?', evidence: 'Manager and project lead observation of AI integration in daily BA workflow, quality of AI-assisted requirements and stakeholder communication, evidence of agentic or advanced AI usage, feedback from junior BAs on AI guidance received.' }
    ], behaviors: BEH_BASE.concat([BEH_LEAD]) }
];
